// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlgen

type GeneratedUploader struct {
	ID  string `json:"id"`
	URL string `json:"url"`
}

type Preview struct {
	Loading bool    `json:"loading"`
	URL     *string `json:"url"`
}
